apiVersion: tyk.tyk.io/v1alpha1
kind: OperatorContext
metadata:
  name: andy-context
  namespace: default
spec:
  secretRef:
    name: tyk-operator-andy-context
    namespace: tyk-operator-system
---
apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin-with-context-andy-org
spec:
  contextRef:
    name: andy-context
    namespace: default
  name: httpbin-with-context-andy-org
  use_keyless: true
  protocol: http
  active: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin-with-context-andy-org
    strip_listen_path: true
---
apiVersion: tyk.tyk.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: httpbin-with-context-andy-org
  namespace: default
spec:
  contextRef:
    name: andy-context
    namespace: default
  name: Org2 Security Policy
  state: active
  active: true
  access_rights_array:
    - name: httpbin-with-context-andy-org
      namespace: default
      versions:
        - Default