apiVersion: v1
kind: Secret
metadata:
  name: tyk-operator-andy-context
  namespace: tyk-operator-system
type: Opaque
data:
  TYK_AUTH: ZDA0NTJkZDc3Y2U0NDk5YzcyNmM5MjE3Yjc3NGI1ZDY=
  TYK_ORG: NjExM2Q4MTcyOTc1MWIwMDAxMTNkMDdj
  TYK_MODE: cHJv
  TYK_URL: aHR0cDovL2Rhc2hib2FyZC1zdmMtdHlrLXByby50eWsuc3ZjLmNsdXN0ZXIubG9jYWw6MzAwMA==
  TYK_TLS_INSECURE_SKIP_VERIFY: dHJ1ZQ==