apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
spec:
  name: httpbin proxy
  protocol: https
  use_keyless: true
  active: true
  proxy:
    target_url: http://httpbin.default.svc.cluster.local:8000
    listen_path: /httpbin
    strip_listen_path: true