apiVersion: v1
kind: Secret
metadata:
  name: tyk-operator-conf
  namespace: tyk
type: Opaque
data:
  TYK_AUTH: YWIxMzFkYTczNTU3NDQwODQyMjg4ZDEwZTIwZTQwZGY=
  TYK_ORG: NjFmOTBkMzI1Zjk0NzYwMDAxMTViYmIw
  TYK_MODE: cHJv
  TYK_URL: aHR0cDovL2hvc3QuZG9ja2VyLmludGVybmFsOjMwMDA=
  TYK_TLS_INSECURE_SKIP_VERIFY: dHJ1ZQ==