apiVersion: v1
kind: Secret
metadata:
  name: tyk-operator-conf
  namespace: tyk-operator-system
type: Opaque
data:
  TYK_AUTH: YTMyZmUzNDdlMzI4NDNhZDYxYWI0MWVmMGRhMjE5NjA=
  TYK_ORG: NjQ2YzdhZjhkNDEzODEwMDAxM2Q4NTIy
  TYK_MODE: cHJv
  TYK_URL: aHR0cHM6Ly9wZXRpdGUtb2ZmaWNlci1hZG0uYXdzLXVzZTEuY2xvdWQtYXJhLnR5ay5pbw==
  TYK_TLS_INSECURE_SKIP_VERIFY: dHJ1ZQ==