apiVersion: apps/v1
kind: Deployment
metadata:
  name: atmlocator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atmlocator
      version: v1
  template:
    metadata:
      labels:
        app: atmlocator
        version: v1
    spec:
      containers:
        - image: docker.io/u1ih/yoisho-atm
          imagePullPolicy: IfNotPresent
          name: atmlocator
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: atmlocator
  labels:
    app: atmlocator
spec:
  ports:
    - name: atmlocator
      port: 8000
      targetPort: 8080
  selector:
    app: atmlocator