apiVersion: tyk.tyk.io/v1alpha1
kind: ApiDefinition
metadata:
  name: httpbin
  namespace: tyk
spec:
  name: httpbin
  api_id: httpbin
  protocol: http
  active: true
  use_keyless: true
  proxy:
    target_url: http://httpbin.org
    listen_path: /httpbin
    strip_listen_path: true
#  use_standard_auth: true
#  strip_auth_data: true
#  enable_ip_blacklisting: true
#  blacklisted_ips:
#    - 172.22.0.1
#  version_data:
#    default_version: Default
#    not_versioned: true
#    versions:
#      Default:
#        name: Default
#        use_extended_paths: true
#        extended_paths:
#          size_limits:
#            - method: POST
#              path: /post
#              size_limit: 50
#  cache_options:
#    cache_timeout: 10
#    cache_all_safe_requests: true
#    enable_cache: true
